#!/bin/bash
# Local Testing Guide
# Run Docker containers locally while testing API from your machine

echo "=================================================="
echo "LOCAL API TESTING SETUP"
echo "=================================================="
echo ""
echo "Step 1: Start Docker containers (with proper hostnames for local testing)"
echo "  Run: docker-compose -f docker-compose.local.yml up -d"
echo ""
echo "Step 2: Verify services are healthy"
echo "  Run: docker-compose -f docker-compose.local.yml ps"
echo ""
echo "Step 3: Run the test script (detects ingestion issues)"
echo "  Run: ./src/data/venv/bin/python3 test_ingestion.py"
echo ""
echo "Step 4: Start the API with logging"
echo "  Run: ./src/data/venv/bin/python3 -m uvicorn src.api_main:api --reload --host 0.0.0.0 --port 8000"
echo ""
echo "Step 5: Test endpoints in another terminal"
echo "  Health check:"
echo "    curl http://localhost:8000/health"
echo ""
echo "  Trigger ingestion (max_pages=2 for quick test):"
echo "    curl -X PUT http://localhost:8000/data?max_pages=2"
echo ""
echo "  Get job postings:"
echo "    curl 'http://localhost:8000/data/postings?columns=title&columns=description'"
echo ""
echo "Step 6: Check logs from API terminal - you should see:"
echo "  - Fetching jobs from API"
echo "  - Storing in SQL database"
echo "  - Storing in NoSQL database"
echo ""
echo "Step 7: Stop everything"
echo "  API terminal: Ctrl+C"
echo "  Docker: docker-compose -f docker-compose.local.yml down"
echo ""
echo "=================================================="
